### ISSUE TITLE
Frontenberg PHP Fatal Errors in Jetpack 6.7 via missing Jetpack_React_Page

### ISSUE THREAD

**Issue by tomjn** [Automattic/jetpack#10558]
An update to Jetpack `v6.7` has broken frontenberg, causing the following PHP fatal error:

```
<b>Fatal error</b>: Uncaught Error: Class 'Jetpack_React_Page' not found in /srv/www/tomjn.com/htdocs/wp-content/plugins/jetpack/class.jetpack-gutenberg.php:208
Stack trace:
#0 /srv/www/tomjn.com/htdocs/wp-includes/class-wp-hook.php(286): Jetpack_Gutenberg::enqueue_block_editor_assets('')
#1 /srv/www/tomjn.com/htdocs/wp-includes/class-wp-hook.php(310): WP_Hook-&gt;apply_filters('', Array)
#2 /srv/www/tomjn.com/htdocs/wp-includes/plugin.php(453): WP_Hook-&gt;do_action(Array)
#3 /srv/www/tomjn.com/htdocs/wp-content/plugins/gutenberg/lib/client-assets.php(1664): do_action('enqueue_block_e...')
#4 /srv/www/tomjn.com/htdocs/wp-includes/class-wp-hook.php(286): gutenberg_editor_scripts_and_styles('')
#5 /srv/www/tomjn.com/htdocs/wp-includes/class-wp-hook.php(310): WP_Hook-&gt;apply_filters(NULL, Array)
#6 /srv/www/tomjn.com/htdocs/wp-includes/plugin.php(453): WP_Hook-&gt;do_action(Array)
#7 /srv/www/tomjn.com/htdocs/wp-includes/script-loader.php(1447): do_action('wp_enqueue_scri...')
#8 /srv/www/tomjn.com/htdocs/wp-includes/class-wp-hook.php(286): in <b>/srv/www/tomjn.com/htdocs/wp-content/plugins/jetpack/class.jetpack-gutenberg.php</b> on line <b>208</b><br />
```

I have corrected the issue by modifying `class.jetpack-gutenberg.php` on line 208 to include a `class_exists` check, which brought the site back, but I do not know what excluding this will have broken.

```
                if ( class_exists( 'Jetpack_React_Page' ) ) {
                        $jp_react_page = new Jetpack_React_Page();
                        wp_localize_script(
                                'jetpack-blocks-editor',
                                'Jetpack_Initial_State',
                                $jp_react_page->get_initial_state()
                        );
                }
                Jetpack::setup_wp_i18n_locale_data();
```

I'm expecting that `Jetpack_React_Page` is only loaded if `is_admin` is true, which is not the case in frontenberg and its child themes

**Comment by simison** [comment]
CC @Automattic/poseidon

**Comment by kraftbj** [comment]
We only need the React page class for `get_initial_state`. Should just extract that function to the Jetpack class or something like that.

**Comment by kraftbj** [comment]
When working on this, we should also resolve https://github.com/Automattic/jetpack/issues/10495 to knock out two birds with one stone.
