### ISSUE TITLE
Fatal error Jetpack version 7.5.1 at test domain with Jetpack running in Safe Mode

### ISSUE THREAD

**Issue by Remzi1993** [Automattic/jetpack#12936]
Jetpack version 7.5.1 has an fatal error when logging in as an editor at our test domain. This way it came to my attention as a WP admin and Sysadmin, with display PHP errors enabled I could detect it had something to do with Jetpack on our development and staging site.

We have a live / production domain at deslotenmaker.com and a test / development domain at test.deslotenmaker.com which runs Jetpack in safe mode.

When I enabled PHP display error, WP admins could also see this error.

#### Steps to reproduce the issue

1. Have a staging website and login as an editor
2. Only 1 word of the error message is show due to bad CSS styleling, browser dev tools you could see the error below:

```
<div class="jp-idc-notice__header__emblem">
<b>Fatal error</b>:  Uncaught Error: Class 'Automattic\Jetpack\Logo' not found in /home/leadmih349/domains/deslotenmaker.com/public_html/test/wp-content/plugins/jetpack/class.jetpack-idc.php:318
Stack trace:
#0 /home/leadmih349/domains/deslotenmaker.com/public_html/test/wp-content/plugins/jetpack/class.jetpack-idc.php(238): Jetpack_IDC-&gt;render_notice_header()
#1 /home/leadmih349/domains/deslotenmaker.com/public_html/test/wp-includes/class-wp-hook.php(286): Jetpack_IDC-&gt;display_idc_notice('')
#2 /home/leadmih349/domains/deslotenmaker.com/public_html/test/wp-includes/class-wp-hook.php(310): WP_Hook-&gt;apply_filters(NULL, Array)
#3 /home/leadmih349/domains/deslotenmaker.com/public_html/test/wp-includes/plugin.php(465): WP_Hook-&gt;do_action(Array)
#4 /home/leadmih349/domains/deslotenmaker.com/public_html/test/wp-admin/admin-header.php(281): do_action('admin_notices')
#5 /home/leadmih349/domains/deslotenmaker.com/public_html/test/wp-admin/admin.php(233): require_once('/home/leadmih34...')
#6 {main}
  thrown in <b>/home/leadmih349/domains/deslotenmaker.com/public_html/test/wp-content/plugins/jetpack/class.jetpack-idc.php</b> on line <b>318</b><br>
	<p>The site is experiencing technical difficulties. Please check your site admin email inbox for instructions.</p></div>
```

**Comment by Remzi1993** [comment]
Hi Jeremy @jeherve 
Your fix works!

I have already applied this on our testing server. Shall I close this issue, because it's fixed?

```
 - use Automattic\Jetpack\Logo as Jetpack_Logo;
 + use Automattic\Jetpack\Assets\Logo as Jetpack_Logo;
```

**Comment by jeherve** [comment]
@Remzi1993 Thanks for giving it a try, and I'm glad that it works.

You don't need to close this issue, it will be automatically closed once the fix I proposed is merged in the development version of Jetpack.
