### ISSUE TITLE
Connection Package: Fatal errors when trying to initialize JSON_API

### ISSUE THREAD

**Issue by DanReyLop** [Automattic/jetpack#16060]
When trying to initialize the JSON API, in some scenarios the XML-RPC server will throw a fatal error. That's because it reaches [this point](https://github.com/Automattic/jetpack/blob/master/packages/connection/legacy/class-jetpack-xmlrpc-server.php#L907), and if Jetpack-the-plugin is not installed, `JETPACK__PLUGIN_DIR` is not defined. `class.json-api.php` obviously doesn't exist either.

In the normal connection flow, when the user isn't connected already, the JSON API initialization logic [bails early,](https://github.com/Automattic/jetpack/blob/master/packages/connection/legacy/class-jetpack-xmlrpc-server.php#L898) so this is not a problem in those cases.

#### Steps to reproduce the issue

- Install the `Client-Example` plugin. DON'T install Jetpack.
- Connect your user and site to Jetpack.
- Change [this](https://github.com/Automattic/client-example/blob/8cb38966fb101cf8e91bc06bdca0f313a80df168/admin/simple-ui/class-connection-simple-ui-admin.php#L32) line in your `Client-Example` plugin to `$this->connected_state   = new Authorizing_State( $this );` . That way, you'll be able to go through the `authorize` flow even if Jetpack is already fully connected.
- Go to the `Client-Example` page, click `Authorize user`, and click the `Authorize` button in wordpress.com.

#### What I expected
The authorization would work, I wouldn't see any fatal errors in my logs.

#### What happened instead
The authorization works (assuming you have the changes made in #16058), but this error appears in the site's logs:

```
[03-Jun-2020 21:59:47 UTC] PHP Warning:  Use of undefined constant JETPACK__PLUGIN_DIR - assumed 'JETPACK__PLUGIN_DIR' (this will throw an Error in a future version of PHP) in /Users/daniel/Projects/client-example/vendor/automattic/jetpack-connection/legacy/class-jetpack-xmlrpc-server.php on line 907
[03-Jun-2020 21:59:47 UTC] PHP Warning:  require_once(JETPACK__PLUGIN_DIRclass.json-api.php): failed to open stream: No such file or directory in /Users/daniel/Projects/client-example/vendor/automattic/jetpack-connection/legacy/class-jetpack-xmlrpc-server.php on line 907
[03-Jun-2020 21:59:47 UTC] PHP Fatal error:  require_once(): Failed opening required 'JETPACK__PLUGIN_DIRclass.json-api.php' (include_path='.:/Applications/MAMP/bin/php/php7.4.2/lib/php') in /Users/daniel/Projects/client-example/vendor/automattic/jetpack-connection/legacy/class-jetpack-xmlrpc-server.php on line 907
[03-Jun-2020 21:59:53 UTC] PHP Fatal error:  Uncaught Error: Class 'Jetpack_Error' not found in /Users/daniel/Projects/client-example/vendor/automattic/jetpack-connection/legacy/class-jetpack-xmlrpc-server.php:244
Stack trace:
#0 /Users/daniel/Projects/wordpress/wp-includes/IXR/class-IXR-server.php(127): Jetpack_XMLRPC_Server->remote_authorize(Array)
#1 /Users/daniel/Projects/wordpress/wp-includes/IXR/class-IXR-server.php(65): IXR_Server->call('jetpack.remoteA...', Array)
#2 /Users/daniel/Projects/wordpress/wp-includes/IXR/class-IXR-server.php(27): IXR_Server->serve('<?xml version="...')
#3 /Users/daniel/Projects/wordpress/wp-includes/IXR/class-IXR-server.php(35): IXR_Server->__construct(Array, false, false)
#4 /Users/daniel/Projects/wordpress/wp-includes/class-wp-xmlrpc-server.php(191): IXR_Server->IXR_Server(Array)
#5 /Users/daniel/Projects/wordpress/xmlrpc.php(86): wp_xmlrpc_server->serve_request()
#6 {main}
  thrown in /Users/daniel/Projects/client-example/vendor/automattic/jetpack-connection/legacy/class-jetpack-xmlrpc-server.php on line 244
```

cc/ @kbrown9

**Comment by kbrown9** [comment]
Thanks - we'll work on a fix for this!

FYI: I needed to make the changes in #16062 to reproduce this bug.
