### ISSUE TITLE
Revue widget makes illegal cross-domain call in AMP mode

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#16922]
#### Steps to reproduce the issue

0. On a site with AMP enabled
1. Add the Revue widget to your site (e.g. use username "caseynewton", as per my example)
2. View the page in AMP mode
3. Submit the subscription form

#### What I expected
To be redirected into revue subscription flow (this is what happens in the non-AMP version)

#### What happened instead
Nothing - console error says:

```
Access to fetch at 'https://www.getrevue.co/profile/caseynewton/add_subscriber?_wp_amp_action_xhr_converted=1&amp&__amp_source_origin=http%3A%2F%2Fgoldsounds3.ngrok.io' from origin 'http://goldsounds3.ngrok.io' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

Chrome also reports the blocked request was a POST to https://www.getrevue.co/profile/caseynewton/add_subscriber?_wp_amp_action_xhr_converted=1&amp&__amp_source_origin=http%3A%2F%2Fgoldsounds3.ngrok.io

The underlying error is:

```
[amp-form] Form submission failed: Error: XHR Failed fetching (https://www.getrevue.co/...): Failed to fetch​​​
    at db (https://cdn.ampproject.org/v0.js:29:169)
    at $a.f.createExpectedError (https://cdn.ampproject.org/v0.js:24:235)
    at https://cdn.ampproject.org/v0.js:147:154
```

**Comment by westonruter** [comment]
This will be fixed with https://github.com/ampproject/amp-wp/issues/4191

The proposed solution I've worked on (which needs to be picked up again) is to implement a local proxy endpoint when a form is pointing to an external domain so that the CORS headers aren't an issue. This will also ensure that redirects work properly. See https://github.com/ampproject/amp-wp/pull/4212.

**Comment by fditrapani** [comment]
@westonruter just wanted to follow up on this issue to see if you were able to resolve it. I had some trouble following the links and can't find a way to test this.

**Comment by jeherve** [comment]
The block is no longer available, so this can be closed.

**Comment by fditrapani** [comment]
Thank you @jeherve!
