### ISSUE TITLE
Getting notice WP_Block_Type_Registry::register was called incorrectly sometimes

### ISSUE THREAD

**Issue by SeBsZ** [Automattic/jetpack#18080]
We've been getting some notices which I've tried to debug but am at a loss.

Here are two example stack traces:
```
ErrorException: User Notice: WP_Block_Type_Registry::register was called <strong>incorrectly</strong>. Block type names must contain a namespace prefix. Example: my-plugin/my-custom-block-type Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.0.0.)
#12 /wordpress/wp-includes/functions.php(5229): _doing_it_wrong
#11 /wordpress/wp-includes/class-wp-block-type-registry.php(72): WP_Block_Type_Registry::register
#10 /wordpress/wp-includes/blocks.php(28): register_block_type
#9 /wp-content/plugins/jetpack/vendor/automattic/jetpack-blocks/src/class-blocks.php(81): Automattic\Jetpack\Blocks::jetpack_register_block
#8 /wp-content/plugins/jetpack/extensions/blocks/calendly/calendly.php(27): Automattic\Jetpack\Extensions\Calendly\register_block
#7 /wordpress/wp-includes/class-wp-hook.php(287): WP_Hook::apply_filters
#6 /wordpress/wp-includes/class-wp-hook.php(311): WP_Hook::do_action
#5 /wordpress/wp-includes/plugin.php(478): do_action
#4 /wordpress/wp-settings.php(546): require_once
#3 /wp-config.php(274): require_once
#2 /wordpress/wp-load.php(42): require_once
#1 /wordpress/wp-blog-header.php(13): require
#0 /index.php(23): null
```

```
ErrorException: User Notice: WP_Block_Type_Registry::register was called <strong>incorrectly</strong>. Block type names must contain a namespace prefix. Example: my-plugin/my-custom-block-type Please see <a href="https://wordpress.org/support/article/debugging-in-wordpress/">Debugging in WordPress</a> for more information. (This message was added in version 5.0.0.)
#11 /wordpress/wp-includes/functions.php(5229): _doing_it_wrong
#10 /wordpress/wp-includes/class-wp-block-type-registry.php(72): WP_Block_Type_Registry::register
#9 /wordpress/wp-includes/blocks.php(28): register_block_type
#8 /wp-content/plugins/jetpack/vendor/automattic/jetpack-blocks/src/class-blocks.php(81): Automattic\Jetpack\Blocks::jetpack_register_block
#7 /wp-content/plugins/jetpack/extensions/blocks/donations/donations.php(27): Automattic\Jetpack\Extensions\Donations\register_block
#6 /wordpress/wp-includes/class-wp-hook.php(287): WP_Hook::apply_filters
#5 /wordpress/wp-includes/class-wp-hook.php(311): WP_Hook::do_action
#4 /wordpress/wp-includes/plugin.php(478): do_action
#3 /wordpress/wp-settings.php(546): require_once
#2 /wp-config.php(269): require_once
#1 /wordpress/wp-load.php(42): require_once
#0 /download.php(4): null
```

The weird part is that I've debugged when this happens, and in the file /wp-content/plugins/jetpack/vendor/automattic/jetpack-blocks/src/class-blocks.php I am seeing the value of $slug is 'jetpack/wp_enqueue_style' and for the latter stack trace $slug is 'jetpack/array_merge'. I don't understand how these function names got here, especially since donations.php contains

```
const FEATURE_NAME = 'donations';
const BLOCK_NAME   = 'jetpack/' . FEATURE_NAME;
```

and calendly.php contains
```
const FEATURE_NAME = 'calendly';
const BLOCK_NAME   = 'jetpack/' . FEATURE_NAME;
```

The code to register a block is
```
Blocks::jetpack_register_block(
		BLOCK_NAME,
		array(
			'render_callback' => __NAMESPACE__ . '\load_assets',
			'plan_check'      => true,
		)
	);
```

Since BLOCK_NAME is a const, I don't see how $slug can become jetpack/wp_enqueue_style or jetpack/array_merge when clearly they should be jetpack/donations and jetpack/calendly?

I realize there may not be enough here for you to reproduce this issue. I'm just hoping this report will help others find it who may have this same issue - or perhaps someone knows what's going on here.

**Comment by jeherve** [comment]
I'm afraid I can't seem to reproduce at the moment. Do you have another plugin active on the site? If so, could you try to deactivate it and see if it helps?

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
