### ISSUE TITLE
Autoloader: Exception when uninstalling Jetpack

### ISSUE THREAD

**Issue by guyasyou** [Automattic/jetpack#18996]
#### Steps to reproduce the issue

By UI
1. Go to Admin -> Plugins in Wordpress
2. Install Jetpack
3. Uninstall Jetpack
4. See error in php error logs

By WP-CLI
1. Install Jetpack `wp plugin install jetpack --activate`
2. Uninstall Jetpack `wp plugin delete jetpack`
3. See error in console

#### What I expected
No errors, just uninstall the plugin

#### What happened instead
The plugin is uninstalled, but the error occurs

```
Fatal error: Uncaught RuntimeException: Failed to locate plugin C:\Users\guyasyou\Desktop\wordpress\wp-content\plugins\jetpack in C:\Users\guyasyou\Desktop\wordpress\wp-content\plugins\jetpack\vendor\jetpack-autoloader\class-plugin-locator.php:48
Stack trace:
#0 C:\Users\guyasyou\Desktop\wordpress\wp-content\plugins\jetpack\vendor\jetpack-autoloader\class-plugins-handler.php(99): Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3cjetpack\Plugin_Locator->find_current_plugin()
#1 C:\Users\guyasyou\Desktop\wordpress\wp-content\plugins\jetpack\vendor\jetpack-autoloader\class-autoloader.php(106): Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3cjetpack\Plugins_Handler->get_active_plugins(false, true)
#2 C:\Users\guyasyou\Desktop\wordpress\wp-includes\class-wp-hook.php(287): Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3cjetpack\Autoloader::Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3cjetpack\{closure}('')
#3 C:\Users\guyasyou\Desktop\wordpress\wp-includes\class-wp in C:\Users\guyasyou\Desktop\wordpress\wp-content\plugins\jetpack\vendor\jetpack-autoloader\class-plugin-locator.php on line 48
PS C:\Users\guyasyou\Desktop\wordpress>
```

The error occurs because of a shutdown hook that is created before uninstall and run after uninstall.
https://github.com/Automattic/jetpack/blob/master/projects/packages/autoloader/src/class-autoloader.php#L80

**Comment by jeherve** [comment]
cc @ObliviousHarmony who worked on #17667.
