### ISSUE TITLE
Sync: Uncaught Exception: Unable to get range edges

### ISSUE THREAD

**Issue by GaryJones** [Automattic/jetpack#19337]
Over the last week, there have been 25 VIP customer applications that have had an "Uncaught Exception: Unable to get range edges" fatal error. The total is 188, but distributed across the week.

#### Steps to reproduce the issue

Not sure - but stack traces are below.

#### What I expected

No fatal error - range edges can be found.

#### What happened instead

Jetpack 9.4:

```
Uncaught Exception: Unable to get range edges in /var/www/wp-content/mu-plugins/jetpack-9.4/vendor/automattic/jetpack-sync/src/replicastore/class-table-checksum.php:559
Stack trace:
#0 /var/www/wp-content/mu-plugins/jetpack-9.4/vendor/automattic/jetpack-sync/src/class-replicastore.php(1362): Automattic\Jetpack\Sync\Replicastore\Table_Checksum->get_range_edges(NULL, NULL)
#1 /var/www/wp-content/mu-plugins/jetpack-9.4/vendor/automattic/jetpack-sync/src/class-replicastore.php(1270): Automattic\Jetpack\Sync\Replicastore->calculate_buckets('postmeta', NULL, NULL)
#2 /var/www/wp-content/mu-plugins/jetpack-9.4/vendor/automattic/jetpack-sync/src/class-replicastore.php(286): Automattic\Jetpack\Sync\Replicastore->checksum_histogram('postmeta', NULL, NULL, NULL)
#3 /var/www/wp-content/mu-plugins/jetpack-9.4/vendor/automattic/jetpack-sync/src/class-actions.php(863): Automattic\Jetpack\Sync\Replicastore->post_meta_checksum()
#4 /var/www/wp-content/mu-plugins/jetpack-9.4/json-endpoints/jetpack/class.jetpack-json-api-sync-endpoint.php(70): Automattic\Jetpack\Sync\Actions::get_sync_status('started,send_st...')
#5 /var/www/wp-content/mu-plugins/jetpack-9.4/json-endpoints/jetpack/class.jetpack-json-api-endpoint.php(30): Jetpack_JSON_API_Sync_Status_Endpoint->result()
#6 /var/www/wp-content/mu-plugins/jetpack-9.4/class.json-api.php(382): Jetpack_JSON_API_Endpoint->callback('/sites/15942265...', '159422659')
#7 /var/www/wp-content/mu-plugins/jetpack-9.4/class.json-api.php(366): WPCOM_JSON_API->process_request(Object(Jetpack_JSON_API_Sync_Status_Endpoint), Array)
#8 /var/www/wp-content/mu-plugins/jetpack-9.4/vendor/automattic/jetpack-connection/legacy/class-jetpack-xmlrpc-server.php(929): WPCOM_JSON_API->serve(false)
#9 /var/www/wp-includes/IXR/class-IXR-server.php(121): Jetpack_XMLRPC_Server->json_api(Array)
#10 /var/www/wp-includes/IXR/class-IXR-server.php(206): IXR_Server->call('jetpack.jsonAPI', Array)
#11 /var/www/wp-includes/IXR/class-IXR-server.php(109): IXR_Server->multiCall(Array)
#12 /var/www/wp-includes/IXR/class-IXR-server.php(59): IXR_Server->call('system.multical...', Array)
#13 /var/www/wp-includes/IXR/class-IXR-server.php(27): IXR_Server->serve('<?xml version="...')
#14 /var/www/wp-includes/IXR/class-IXR-server.php(35): IXR_Server->__construct(Array, false, false)
#15 /var/www/wp-includes/class-wp-xmlrpc-server.php(191): IXR_Server->IXR_Server(Array)
#16 /var/www/xmlrpc.php(87): wp_xmlrpc_server->serve_request()
#17 {main}
```

Jetpack 9.5

```
Uncaught Exception: Unable to get range edges in /var/www/wp-content/mu-plugins/jetpack-9.5/vendor/automattic/jetpack-sync/src/replicastore/class-table-checksum.php:591
Stack trace:
#0 /var/www/wp-content/mu-plugins/jetpack-9.5/vendor/automattic/jetpack-sync/src/class-replicastore.php(1362): Automattic\Jetpack\Sync\Replicastore\Table_Checksum->get_range_edges(NULL, NULL)
#1 /var/www/wp-content/mu-plugins/jetpack-9.5/vendor/automattic/jetpack-sync/src/class-replicastore.php(1270): Automattic\Jetpack\Sync\Replicastore->calculate_buckets('postmeta', NULL, NULL)
#2 /var/www/wp-content/mu-plugins/jetpack-9.5/vendor/automattic/jetpack-sync/src/class-replicastore.php(1173): Automattic\Jetpack\Sync\Replicastore->checksum_histogram('postmeta')
#3 /var/www/wp-content/mu-plugins/jetpack-9.5/json-endpoints/jetpack/class.jetpack-json-api-sync-endpoint.php(79): Automattic\Jetpack\Sync\Replicastore->checksum_all()
#4 /var/www/wp-content/mu-plugins/jetpack-9.5/json-endpoints/jetpack/class.jetpack-json-api-endpoint.php(30): Jetpack_JSON_API_Sync_Check_Endpoint->result()
#5 /var/www/wp-content/mu-plugins/jetpack-9.5/class.json-api.php(382): Jetpack_JSON_API_Endpoint->callback('/sites/18260523...', '182605232')
#6 /var/www/wp-content/mu-plugins/jetpack-9.5/class.json-api.php(366): WPCOM_JSON_API->process_request(Object(Jetpack_JSON_API_Sync_Check_Endpoint), Array)
#7 /var/www/wp-content/mu-plugins/jetpack-9.5/vendor/automattic/jetpack-connection/legacy/class-jetpack-xmlrpc-server.php(929): WPCOM_JSON_API->serve(false)
#8 /var/www/wp-includes/IXR/class-IXR-server.php(121): Jetpack_XMLRPC_Server->json_api(Array)
#9 /var/www/wp-includes/IXR/class-IXR-server.php(211): IXR_Server->call('jetpack.jsonAPI', Array)
#10 /var/www/wp-includes/IXR/class-IXR-server.php(109): IXR_Server->multiCall(Array)
#11 /var/www/wp-includes/IXR/class-IXR-server.php(59): IXR_Server->call('system.multical...', Array)
#12 /var/www/wp-includes/IXR/class-IXR-server.php(27): IXR_Server->serve('<?xml version="...')
#13 /var/www/wp-includes/IXR/class-IXR-server.php(35): IXR_Server->__construct(Array, false, false)
#14 /var/www/wp-includes/class-wp-xmlrpc-server.php(191): IXR_Server->IXR_Server(Array)
#15 /var/www/xmlrpc.php(87): wp_xmlrpc_server->serve_request()
#16 {main}
```

**Comment by mdbitz** [comment]
The issue is a bad query concerning postmeta.

We need to simplify it so that the range calculation doesn't use the meta whitelist. Instead it gets the post ranges and then we go from there into buckets. It means the buckets will include posts that may not have certain meta but that gets filtered out in the actual checksums.
