### ISSUE TITLE
Crash of Jetpack Beta plugin on Dreamhost "Dreampress" managed instance

### ISSUE THREAD

**Issue by gravityrail** [Automattic/jetpack#21268]
### Impacted plugin

Beta

### Steps to Reproduce

1. On a site installed on Dreampress, e.g. www.goldsounds.com...
2. The Jetpack Beta plugin was automatically upgraded to 3.0.2
3. I got an error and couldn't load any pages in wp-admin and needed to enter recovery mode to deactivate Jetpack Beta

Note that deactivating the beta plugin resulted in the following error:

```
The plugin jetpack-dev/jetpack.php has been deactivated due to an error: Plugin file does not exist.
```

I then reinstalled regular Jetpack and it worked fine (after I deactivated an old version of Jetpack Boost). However, trying to install the Jetpack Beta plugin again resulted in the same error pasted below.

### A clear and concise description of what you expected to happen.

Jetpack Beta should have upgraded without errors

### What actually happened

I got the following error:

```
 This plugin failed to load properly and is paused during recovery mode.

An error of type E_ERROR was caused in line 121 of the file /home/$SOME_DIR/goldsounds.com/wp-content/plugins/jetpack-beta-master/src/class-plugin.php. 
Error message: Uncaught Automattic\JetpackBeta\PluginDataException: Failed to download list of plugins. Check your Internet connection. 
in /home/$SOME_DIR/goldsounds.com/wp-content/plugins/jetpack-beta-master/src/class-plugin.php:121 
Stack trace: #0 /home/$SOME_DIR/goldsounds.com/wp-content/plugins/jetpack-beta-master/src/class-hooks.php(352): Automattic\JetpackBeta\Plugin::get_all_plugins() 
#1 /home/$SOME_DIR/goldsounds.com/wp-includes/class-wp-hook.php(303): Automattic\JetpackBeta\Hooks->admin_bar_menu(Object(WP_Admin_Bar)) 
#2 /home/$SOME_DIR/goldsounds.com/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters(NULL, Array) 
#3 /home/$SOME_DIR/goldsounds.com/wp-includes/plugin.php(518): WP_Hook->do_action(Array) 
#4 /home/$SOME_DIR/goldsounds.com/wp-includes/admin-bar.php(95): do_action_ref_array('admin_bar_menu', Array) 
#5 /home/$SOME_DIR/goldsounds.com/wp-includes/class-wp-hook.php(303): wp_admin_bar_render('') 
#6 /home/$SOME_DIR/goldsounds.com/wp-includes/class-wp-hook.php(327): WP_Hook->apply_filters('', Array) 
#7 /
```

Screenshot:

<img width="1620" alt="beta-error" src="https://user-images.githubusercontent.com/51896/135664804-c6c218c7-1483-46c5-9488-25f33c255c8f.png">

### Other information

WP version 5.8.1

### Operating System

Linux

### Browser

Chrome/Chromium

**Comment by jeherve** [comment]
This doesn't seem to be an issue anymore. Closing.
