### ISSUE TITLE
Beta Plugin: Jetpack Beta Report 1

### ISSUE THREAD

**Issue by computerghar** [Automattic/jetpack#23210]
### Impacted plugin

Jetpack, Beta

### Steps to Reproduce

1. Error_log Wordpress

### A clear and concise description of what you expected to happen.

[03-Mar-2022 00:48:38 UTC] PHP Fatal error:  Uncaught Error: Class 'WP_CLI_Command' not found in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php:17
Stack trace:
#0 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-php-autoloader.php(90): require()
#1 [internal function]: Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\PHP_Autoloader::load_class('Automattic\\Jetp...')
#2 [internal function]: spl_autoload_call('Automattic\\Jetp...')
#3 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-version-loader.php(108): class_exists('Automattic\\Jetp...', true)
#4 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-upgrade-handler.php(57): Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\Version_Loader->load_classes_in_path('/home3/a1641ok5...')
#5 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/ve in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php on line 17
[03-Mar-2022 01:48:42 UTC] PHP Fatal error:  Uncaught Error: Class 'WP_CLI_Command' not found in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php:17
Stack trace:
#0 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-php-autoloader.php(90): require()
#1 [internal function]: Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\PHP_Autoloader::load_class('Automattic\\Jetp...')
#2 [internal function]: spl_autoload_call('Automattic\\Jetp...')
#3 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-version-loader.php(108): class_exists('Automattic\\Jetp...', true)
#4 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-upgrade-handler.php(57): Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\Version_Loader->load_classes_in_path('/home3/a1641ok5...')
#5 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/ve in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php on line 17
[03-Mar-2022 02:48:44 UTC] PHP Fatal error:  Uncaught Error: Class 'WP_CLI_Command' not found in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php:17
Stack trace:
#0 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-php-autoloader.php(90): require()
#1 [internal function]: Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\PHP_Autoloader::load_class('Automattic\\Jetp...')
#2 [internal function]: spl_autoload_call('Automattic\\Jetp...')
#3 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-version-loader.php(108): class_exists('Automattic\\Jetp...', true)
#4 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-upgrade-handler.php(57): Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\Version_Loader->load_classes_in_path('/home3/a1641ok5...')
#5 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/ve in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php on line 17
[03-Mar-2022 03:48:40 UTC] PHP Fatal error:  Uncaught Error: Class 'WP_CLI_Command' not found in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php:17
Stack trace:
#0 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-php-autoloader.php(90): require()
#1 [internal function]: Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\PHP_Autoloader::load_class('Automattic\\Jetp...')
#2 [internal function]: spl_autoload_call('Automattic\\Jetp...')
#3 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-version-loader.php(108): class_exists('Automattic\\Jetp...', true)
#4 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-upgrade-handler.php(57): Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\Version_Loader->load_classes_in_path('/home3/a1641ok5...')
#5 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/ve in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php on line 17

### What actually happened

 [03-Mar-2022 00:48:38 UTC] PHP Fatal error:  Uncaught Error: Class 'WP_CLI_Command' not found in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php:17
Stack trace:
#0 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-php-autoloader.php(90): require()
#1 [internal function]: Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\PHP_Autoloader::load_class('Automattic\\Jetp...')
#2 [internal function]: spl_autoload_call('Automattic\\Jetp...')
#3 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-version-loader.php(108): class_exists('Automattic\\Jetp...', true)
#4 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-upgrade-handler.php(57): Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\Version_Loader->load_classes_in_path('/home3/a1641ok5...')
#5 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/ve in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php on line 17
[03-Mar-2022 01:48:42 UTC] PHP Fatal error:  Uncaught Error: Class 'WP_CLI_Command' not found in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php:17
Stack trace:
#0 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-php-autoloader.php(90): require()
#1 [internal function]: Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\PHP_Autoloader::load_class('Automattic\\Jetp...')
#2 [internal function]: spl_autoload_call('Automattic\\Jetp...')
#3 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-version-loader.php(108): class_exists('Automattic\\Jetp...', true)
#4 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-upgrade-handler.php(57): Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\Version_Loader->load_classes_in_path('/home3/a1641ok5...')
#5 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/ve in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php on line 17
[03-Mar-2022 02:48:44 UTC] PHP Fatal error:  Uncaught Error: Class 'WP_CLI_Command' not found in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php:17
Stack trace:
#0 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-php-autoloader.php(90): require()
#1 [internal function]: Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\PHP_Autoloader::load_class('Automattic\\Jetp...')
#2 [internal function]: spl_autoload_call('Automattic\\Jetp...')
#3 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-version-loader.php(108): class_exists('Automattic\\Jetp...', true)
#4 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-upgrade-handler.php(57): Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\Version_Loader->load_classes_in_path('/home3/a1641ok5...')
#5 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/ve in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php on line 17
[03-Mar-2022 03:48:40 UTC] PHP Fatal error:  Uncaught Error: Class 'WP_CLI_Command' not found in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php:17
Stack trace:
#0 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-php-autoloader.php(90): require()
#1 [internal function]: Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\PHP_Autoloader::load_class('Automattic\\Jetp...')
#2 [internal function]: spl_autoload_call('Automattic\\Jetp...')
#3 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-version-loader.php(108): class_exists('Automattic\\Jetp...', true)
#4 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/vendor/jetpack-autoloader/class-upgrade-handler.php(57): Automattic\Jetpack\Autoloader\jpf11009ded9fc4592b6a05b61ce272b3c_jetpackⓥ10_8_a_2\Version_Loader->load_classes_in_path('/home3/a1641ok5...')
#5 /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/ve in /home3/a1641ok5/public_html/wp-content/plugins/jetpack-dev/jetpack_vendor/automattic/jetpack-search/src/class-cli.php on line 17

### Operating System

Windows

### Browser

Chrome/Chromium

### Browser Version(s)

Chrome is up to date Version 98.0.4758.102 (Official Build) (64-bit)

**Comment by jeherve** [comment]
Thanks for the report. We fixed this issue in #23207, it should be okay now.
