### ISSUE TITLE
Fatal error PHP 8.1

### ISSUE THREAD

**Issue by knutsp** [Automattic/jetpack#23835]
### Impacted plugin

Jetpack

### Steps to Reproduce

1. Install [Passwords Evolved](https://wordpress.org/plugins/passwords-evolved/) plugin
2. Install Jetpack 10.7 - Connect - Select Free plan
3. Upgrade to Jetpack 10.8
4. Navigate o a dashboard or front end page

### A clear and concise description of what you expected to happen.

Everything to be as normal, no errors

### What actually happened

Page displays "Fatal error occurred on this site" (or similar) message created by WordPress Fatal Error handler.

### Other information

`PHP Fatal error:  Uncaught InvalidArgumentException: Container doesn't have a value stored for the "password.generator" key. in /.../wp-content/plugins/passwords-evolved/src/DependencyInjection/Container.php:94
Stack trace:
#0 /.../wp-content/plugins/passwords-evolved/src/Plugin.php(79): PasswordsEvolved\DependencyInjection\Container->offsetGet()
#1 /.../wp-content/plugins/passwords-evolved/pluggable.php(59): PasswordsEvolved\Plugin->get_password_generator()
#2 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-connection/src/class-client.php(132): wp_generate_password()
#3 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-connection/src/class-client.php(37): Automattic\Jetpack\Connection\Client::build_signed_request()
#4 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-connection/src/class-client.php(453): Automattic\Jetpack\Connection\Client::remote_request()
#5 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-search/src/class-plan.php(51): Automattic\Jetpack\Connection\Client::wpcom_json_api_request_as_blog()
#6 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-search/src/class-plan.php(67): Automattic\Jetpack\Search\Plan->get_plan_info_from_wpcom()
#7 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-search/src/class-plan.php(71): Automattic\Jetpack\Search\Plan->get_plan_info()
#8 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-search/src/class-plan.php(97): Automattic\Jetpack\Search\Plan->get_plan_info()
#9 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-search/src/initializers/class-initializer.php(208): Automattic\Jetpack\Search\Plan->supports_search()
#10 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-search/src/initializers/class-initializer.php(51): Automattic\Jetpack\Search\Initializer::is_search_supported()
#11 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-config/src/class-config.php(233): Automattic\Jetpack\Search\Initializer::init()
#12 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-config/src/class-config.php(169): Automattic\Jetpack\Config->enable_search()
#13 /.../wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-config/src/class-config.php(114): Automattic\Jetpack\Config->ensure_feature()
#14 /.../wp-includes/class-wp-hook.php(307): Automattic\Jetpack\Config->on_plugins_loaded()
#15 /.../wp-includes/class-wp-hook.php(331): WP_Hook->apply_filters()
#16 /.../wp-includes/plugin.php(474): WP_Hook->do_action()
#17 /.../wp-settings.php(450): do_action()
#18 /../wp-config.php(118): require_once('/.../...')
#19 /.../wp-load.php(55): require_once('/.../...')
#20 /.../wp-admin/admin.php(34): require_once('/...')
#21 /.../wp-admin/index.php(10): require_once('/...')
#22 {main}
  thrown in /.../wp-content/plugins/passwords-evolved/src/DependencyInjection/Container.php on line 94`

Same happened with update to Jetpack 10.1, bit later fixed. See https://github.com/Automattic/jetpack/issues/21165

### Operating System

Linux

### Browser

Other / Not applicable

**Comment by jeherve** [comment]
cc @kraftbj since you worked on #21243.

**Comment by austinginder** [comment]
Just following up with a few observations. This PHP fatal error seems to go away if the WordPress sites are able to complete a full site sync with Jetpack or resolve Jetpack connection issues. Apparently I have a number of sites where the Jetpack connection is broken and needs to be manually resolved. Just thought I'd mention in case that helps with troubleshooting.

**Comment by jeherve** [comment]
@austinginder Thanks for the extra details. 

Could you clarify whether your sites use a specific way of loading plugins (e.g. all required via composer) or if they're installed regularly?

**Comment by austinginder** [comment]
No all of the plugins are loaded the standard way. These sites are just experiencing a common Jetpack connection issue. This is what `wp jetpack status` looks like.

![Screenshot from 2022-06-18 21-51-20](https://user-images.githubusercontent.com/110346/174579705-002121c8-1a73-4e0c-b307-1dbbbde5994d.png)

Running `wp jetpack test-connection` reports "Error: It looks like your Jetpack connection is broken.  Try disconnecting from WordPress.com then reconnecting.".

I also trying running `wp jetpack sync start` on these sites before I noticed the connection was broken and it endless says "Sent data to WordPress.com". After 24hrs of sending data to Jetpack I concluded it was just stuck in a loop and I killed the process.

I suspect fixing the Jetpack connection issue hides the fact that this plugin conflict exists, thus making it harder to reproduce.

**Comment by jeherve** [comment]
Thanks for the extra details. I broke a test site to try to reproduce, but no luck. Even though my connection is broken and Sync is stuck, I do not get a fatal when activating the Passwords Evolved plugin. Did you maybe experience the fatal at a different time, when taking a different action on the site?
<img width="711" alt="Screen Shot 2022-06-21 at 19 06 10" src="https://user-images.githubusercontent.com/426388/174858135-e8eca383-8e2c-498d-acb9-6d116a2eea24.png">

If you get the chance and have the option to do so, it may be worth trying to patch your installation with #24688, and see how that goes?

Thank you!

**Comment by austinginder** [comment]
@jeherve The PHP errors happen when attempting to sign into the backend. Front-end is fine. Couldn't even load the `wp-login.php` page.

I tried your patch and it actually made things worse. Both front-end and backend were giving PHP fatal errors.

![Screenshot from 2022-06-21 14-38-52](https://user-images.githubusercontent.com/110346/174874446-2d6c49f9-1131-4321-b077-ac2a36c6167a.png)

Looks like the same errors in the error log.

```
2022/06/21 18:40:29 [error] 55743#55743: *154353 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught InvalidArgumentException: Container doesn't have a value stored for the "password.generator" key. in /www/public/wp-content/plugins/passwords-evolved/src/DependencyInjection/Container.php:94
Stack trace:
#0 /www/public/wp-content/plugins/passwords-evolved/src/Plugin.php(79): PasswordsEvolved\DependencyInjection\Container->offsetGet('password.genera...')
#1 /www/public/wp-content/plugins/passwords-evolved/pluggable.php(59): PasswordsEvolved\Plugin->get_password_generator()
#2 /www/public/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-connection/src/class-client.php(136): wp_generate_password(10, false)
#3 /www/public/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-connection/src/class-client.php(37): Automattic\Jetpack\Connection\Client::build_signed_request(Array, NULL)
#4 /www/public/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-connection/src/class-c" while reading response 
```

**Comment by cliffordp** [comment]
FYI: Issue remains on latest versions of Jetpack and Passwords Evolved :'(
