### ISSUE TITLE
Gravity Forms Geolocation addon conflict

### ISSUE THREAD

**Issue by cena** [Automattic/jetpack#30164]
### Impacted plugin

Jetpack

### Quick summary

Reported in 6199657-zen

Error message:

```
PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function jetpack_oembed_timeout_override(), 1 passed in /home/beads1234/public_html/nameyourprice.market/wp-includes/class-wp-hook.php on line 308 and exactly 2 expected in /home/beads1234/public_html/nameyourprice.market/wp-content/plugins/jetpack/modules/shortcodes/others.php:29 
```

Complete log entry from Pressable (my test site):

```
PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function jetpack_oembed_timeout_override(), 1 passed in /wordpress/core/6.2/wp-includes/class-wp-hook.php on line 308 and exactly 2 expected in /wordpress/plugins/jetpack/12.1-a.7/modules/shortcodes/others.php:29 Stack trace: #0 /wordpress/core/6.2/wp-includes/class-wp-hook.php(308): jetpack_oembed_timeout_override(30) #1 /wordpress/core/6.2/wp-includes/plugin.php(205): WP_Hook->apply_filters(30, Array) #2 /srv/htdocs/wp-content/plugins/gravityformsgeolocation/includes/class-gf-google-places-api.php(82): apply_filters('http_request_ti...', 30) #3 /srv/htdocs/wp-content/plugins/gravityformsgeolocation/includes/class-gf-google-places-api.php(135): Gravity_Forms\Gravity_Forms_Geolocation\GF_Google_Places_API->make_request('autocomplete/js...') #4 /srv/htdocs/wp-content/plugins/gravityformsgeolocation/class-gf-geolocation.php(229): Gravity_Forms\Gravity_Forms_Geolocation\GF_Google_Places_API->validate_api_key() #5 /srv/htdocs/wp-content/plugins/gravityformsgeolocation/class-gf-geolocation.php(985): Gravity_Forms\Gravity_Forms_Geolocation\GF_Geolocation->initialize_api() #6 [internal function]: Gravity_Forms\Gravity_Forms_Geolocation\GF_Geolocation->validate_google_places_api_key('AIzaSyAUbat4odq...', Object(Gravity_Forms\Gravity_Forms\Settings\Fields\Text)) #7 /srv/htdocs/wp-content/plugins/gravityforms/includes/settings/fields/class-base.php(436): call_user_func_array(Array, Array) #8 /srv/htdocs/wp-content/plugins/gravityforms/includes/settings/fields/class-text.php(59): Gravity_Forms\Gravity_Forms\Settings\Fields\Base->get_container_classes() #9 /srv/htdocs/wp-content/plugins/gravityforms/includes/settings/fields/class-base.php(218): Gravity_Forms\Gravity_Forms\Settings\Fields\Text->markup() #10 /srv/htdocs/wp-content/plugins/gravityforms/includes/settings/class-settings.php(906): Gravity_Forms\Gravity_Forms\Settings\Fields\Base->prepare_markup() #11 /srv/htdocs/wp-content/plugins/gravityforms/includes/settings/class-settings.php(857): Gravity_Forms\Gravity_Forms\Settings\Settings->render_field(Object(Gravity_Forms\Gravity_Forms\Settings\Fields\Text)) #12 /srv/htdocs/wp-content/plugins/gravityforms/includes/settings/class-settings.php(637): Gravity_Forms\Gravity_Forms\Settings\Settings->render_section(Array) #13 /srv/htdocs/wp-content/plugins/gravityforms/includes/addon/class-gf-addon.php(4809): Gravity_Forms\Gravity_Forms\Settings\Settings->render() #14 /wordpress/core/6.2/wp-includes/class-wp-hook.php(308): GFAddOn->plugin_settings_page('') #15 /wordpress/core/6.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #16 /wordpress/core/6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #17 /srv/htdocs/wp-content/plugins/gravityforms/settings.php(144): do_action('gform_settings_...') #18 /srv/htdocs/wp-content/plugins/gravityforms/gravityforms.php(3418): GFSettings::settings_page() #19 /wordpress/core/6.2/wp-includes/class-wp-hook.php(308): GFForms::settings_page('') #20 /wordpress/core/6.2/wp-includes/class-wp-hook.php(332): WP_Hook->apply_filters('', Array) #21 /wordpress/core/6.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array) #22 /wordpress/core/6.2/wp-admin/admin.php(259): do_action('forms_page_gf_s...') #23 {main} thrown in /wordpress/plugins/jetpack/12.1-a.7/modules/shortcodes/others.php on line 29
```

### Steps to reproduce

1 - Activate Jetpack
2 - install/activate Gravity Forms
3 - install/activate GF Geolocation addon
4 - create Google Places API key
5 - enter API key in Forms->Settings->Geolocation, save.

### A clear and concise description of what you expected to happen.

To be able to use Gravity Forms & Geolocation addon with Jetpack active.

### What actually happened

Following the steps above, Geolocation crashes:

<img width="604" alt="SCR-20230418-hsd" src="https://user-images.githubusercontent.com/19334/232873679-475e4949-5bc6-4158-9f98-dede8fe9c4ed.png">

Geolocation logging shows:

```
2023-04-18 19:17:12.998019 - DEBUG --> Gravity_Forms\Gravity_Forms_Geolocation\GF_Google_Places_API::make_request(): Making request to: autocomplete/json?input=Weaver&types=address&key=AIzaSyAUbat4odqhbIcs3bFoXXX9cID5pJuhvFHQ 
```

### Impact

One

### Available workarounds?

No but the platform is still usable

### Logs or notes

Other notes:

- turn off Geolocation, re-activate, error above remains 
- delete and reinstall Geolocation, error above remains
- turn off JP, error corrected
- entered API key and saved (no error)
- tried to turn JP on again after key entered; crashed as above. 
- tested with Shortcode Embeds both off and on

Gravity Forms support: "As the PHP error message logged indicates the issue is caused by the file /wp-content/plugins/jetpack/modules/shortcodes/others.php "

**Comment by jeherve** [comment]
Do you happen to have access to the addon code? Jetpack relies on Core's `http_request_timeout` filter here:
https://github.com/Automattic/jetpack/blob/fd90454188d21d1bbcf16ff50dbdb74803729ccb/projects/plugins/jetpack/modules/shortcodes/others.php#L37

That filter [expects 2 parameters](https://developer.wordpress.org/reference/hooks/http_request_timeout/), and they are provided in Jetpack. I wonder if the addon may only be providing one parameter when they hook into that filter.

Could you take a look, if you have the chance?

Thank you!

**Comment by jeherve** [comment]
Closing this for now because of the lack of activity on this. We can always reopen in the future if needed.
