### ISSUE TITLE
Memberships: fatal "Jetpack_Memberships" not found

### ISSUE THREAD

**Issue by samiff** [Automattic/jetpack#31258]
While deploying Jetpack v12.3-a.1 to WoA sites, we encountered the following across several sites:

```
PHP Fatal error:  Uncaught Error: Class "Jetpack_Memberships" not found in /wordpress/plugins/jetpack/12.3-a.1/modules/subscriptions/views.php:350
Stack trace:
#0 /wordpress/plugins/jetpack/12.3-a.1/modules/subscriptions/views.php(144): Jetpack_Subscriptions_Widget::render_widget_subscription_form(Array, Array, '')
#1 /wordpress/core/6.2.2/wp-includes/class-wp-widget.php(394): Jetpack_Subscriptions_Widget->widget(Array, Array)
#2 /wordpress/core/6.2.2/wp-includes/widgets.php(835): WP_Widget->display_callback(Array, Array)
#3 /srv/htdocs/wp-content/themes/really-simple/sidebar.php(11): dynamic_sidebar('really-simple-s...')
#4 /wordpress/core/6.2.2/wp-includes/template.php(783): require_once('/srv/htdocs/wp-...')
#5 /wordpress/core/6.2.2/wp-includes/template.php(718): load_template('/srv/htdocs/wp-...', true, Array)
#6 /wordpress/core/6.2.2/wp-includes/general-template.php(136): locate_template(Array, true, true, Array)
#7 /srv/htdocs/wp-content/themes/really-simple/archive.php(44): get_sidebar()
#8 /wordpress/core/6.2.2/wp-includes/template-loader.php(106): include('/srv/htdocs/wp-...')
#9 /wordpress/core/6.2.2/wp-blog-header.php(19): require_once('/wordpress/core...')
#10 /wordpress/core/6.2.2/index.php(17): require('/wordpress/core...')
#11 {main}
  thrown in /wordpress/plugins/jetpack/12.3-a.1/modules/subscriptions/views.php on line 350
```

This error is likely related to changes done in #30807

CC: @romarioraffington @millerf @n3f Could one of you have a look please.

Initial thoughts are that a require got missed somewhere, for example: https://github.com/Automattic/jetpack/pull/30807/files#r1198462609

Internal references:

- p1686162943989619-slack-C01U2KGS2PQ
- p9o2xV-394-p2#comment-7701

**Comment by romarioraffington** [comment]
@samiff, we have a fix ready. I couldn't reproduce the issue on WoA using a Jurassic Ninja site.  Any tips on how to reproduce this?
