### ISSUE TITLE
Subscriber block js error on template edit

### ISSUE THREAD

**Issue by lezama** [Automattic/jetpack#31866]
When navigating templates in the Site Editor I am getting the following js error:

```
react-dom.js?ver=18:1 Warning: Cannot update a component (`bp`) while rendering a different component (`SubscriptionEdit`). To locate the bad setState() call inside `SubscriptionEdit`, follow the stack trace as described in https://reactjs.org/link/setstate-in-render
    at SubscriptionEdit (webpack-internal:///./extensions/blocks/subscriptions/edit.js:78:5)
    at div
    at ThemeProvider (webpack-internal:///../../js-packages/components/components/theme-provider/index.tsx:125:5)
    at div
```

**Comment by jeherve** [comment]
@lezama Do you still run into this today?
