### ISSUE TITLE
Unhandled exception: Call to undefined method is_custom_queue_table_enabled() WP 6.3 Astra 4.2.2 Jetpack 12.5

### ISSUE THREAD

**Issue by nkomarov** [Automattic/jetpack#32644]
### Impacted plugin

Jetpack

### Quick summary

On a self-hosted freshly installed WP, when I try to login to the admin panel, it always fails with the "wrong password" until I reset my password. 

After that it lets me log in.

Then suddenly I saw an email from my WP saying there was an uncaught exception in Jetpack. I believe that this unhandled exception prevents me from logging in.

### Steps to reproduce

Install a clean WP, install and activate a number of plugins including the Jetpack.
Try to login and fail.

### A clear and concise description of what you expected to happen.

I would expect my WP installation let me log in.

### What actually happened

When I try to login to the admin panel, it always fails with the "wrong password" until I reset my password. 
After that it lets me log in.

### Impact

Some (< 50%)

### Available workarounds?

No and the platform is unusable

### Platform (Simple and/or Atomic)

Self-hosted

### Logs or notes

Unhandled exception information:

Версия WordPress 6.3
Текущая тема: Astra (версия 4.2.2)
Проблемный плагин: Jetpack (версия 12.5) Версия PHP 7.4.33 Подробности ошибки ===================================
Ошибка с типом E_ERROR возникла на строке 64 файла /home/sites/25b/d/da6f09a1de/public_html/new/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-queue.php. Сообщение об ошибке: Uncaught Error: Call to undefined method Automattic\Jetpack\Sync\Settings::is_custom_queue_table_enabled() in /home/sites/25b/d/da6f09a1de/public_html/new/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-queue.php:64
Stack trace:
#0 /home/sites/25b/d/da6f09a1de/public_html/new/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-listener.php(465): Automattic\Jetpack\Sync\Queue->__construct('sync')
#1 /home/sites/25b/d/da6f09a1de/public_html/new/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-listener.php(75): Automattic\Jetpack\Sync\Listener->set_defaults()
#2 /home/sites/25b/d/da6f09a1de/public_html/new/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-listener.php(63): Automattic\Jetpack\Sync\Listener->__construct()
#3 /home/sites/25b/d/da6f09a1de/public_html/new/wp-content/plugins/jetpack/jetpack_vendor/automattic/jetpack-sync/src/class-actions.php(721): Automattic\Jetpack\Sync\Listener::get_instance()
#

**Comment by nkomarov** [comment]
### Begin System Info (Generated at 2023-08-23 16:52:27) ###

-- Email Log Configuration --

Email Log Version:                  2.4.8
Number of Logs:                     21
Email Log DB Version:               0.3

-- Email Log Addon License --

- More Fields
- Resend Email
- Auto Delete Logs
- Forward Email
- Export Logs

-- Site Info --

Site URL:                 (hidden)
Home URL:                 (hidden)
Multisite:                No
Active Theme:             Astra 4.2.2

-- WordPress Configuration --

Version:                  6.3
Language:                 ru_RU
Permalink Structure:      /%postname%/
WP Table Prefix:          c7_
GMT Offset:               3
Memory Limit:             40M
Memory Max Limit:         256M
ABSPATH:                  /home/sites/25b/d/da6f09a1de/public_html/new/
WP_DEBUG:                 Disabled
WP_DEBUG_LOG:              Disabled
SAVEQUERIES:              Not set
WP_SCRIPT_DEBUG:          Not set
DISABLE_WP_CRON:          Not set
WP_CRON_LOCK_TIMEOUT:     60
EMPTY_TRASH_DAYS:         30

Registered Post types:    post, page, attachment, revision, nav_menu_item, custom_css, customize_changeset, oembed_cache, user_request, wp_block, wp_template, wp_template_part, wp_global_styles, wp_navigation, e-landing-page, elementor_library, viwec_template, product, product_variation, shop_order, shop_order_refund, shop_coupon, shop_order_placehold, courses, lesson, tutor_quiz, topics, tutor_assignments, tutor_enrolled, wpforms, udb_widgets, udb_admin_page
post                      publish=0, future=0, draft=0, pending=0, private=0, trash=1, auto-draft=1, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
page                      publish=24, future=0, draft=1, pending=0, private=0, trash=1, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
attachment                publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=28, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
revision                  publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=40, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
nav_menu_item             publish=8, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
custom_css                publish=1, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
customize_changeset       publish=0, future=0, draft=0, pending=0, private=0, trash=10, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
oembed_cache              publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
user_request              publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
wp_block                  publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
wp_template               publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
wp_template_part          publish=1, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
wp_global_styles          publish=2, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
wp_navigation             publish=1, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
e-landing-page            publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
elementor_library         publish=2, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
viwec_template            publish=14, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
product                   publish=6, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
product_variation         publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
shop_order                publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
shop_order_refund         publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
shop_coupon               publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
shop_order_placehold      publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
courses                   publish=1, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
lesson                    publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
tutor_quiz                publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
topics                    publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
tutor_assignments         publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
tutor_enrolled            publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
wpforms                   publish=2, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
udb_widgets               publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 
udb_admin_page            publish=0, future=0, draft=0, pending=0, private=0, trash=0, auto-draft=0, inherit=0, request-pending=0, request-confirmed=0, request-failed=0, request-completed=0, wc-pending=0, wc-processing=0, wc-on-hold=0, wc-completed=0, wc-cancelled=0, wc-refunded=0, wc-failed=0, wc-checkout-draft=0, 

-- WordPress Active Plugins --

Admin Menu Search: 1.2
Akismet Anti-Spam: Spam Protection: 5.2
Analytics Germanized for Google Analytics: 1.6.2
Astra Pro: 4.1.7
Burst Statistics - Privacy-Friendly Analytics for WordPress: 1.4.5
Check & Log Email: 1.0.7
Complianz | GDPR/CCPA Cookie Consent: 6.5.3
Customer Reviews for WooCommerce: 5.32.0
Duplicate Page: 4.5.2
Duplicator: 1.5.5.1
Elementor: 3.15.3
Element Pack Lite - Addons for Elementor: 5.3.1
Email Log: 2.4.8
Email Template Customizer for WooCommerce: 1.2.0
Essential Addons for Elementor: 5.8.6
Essential Blocks: 4.2.0
Germanized for WooCommerce: 3.13.3
Google Listings and Ads: 2.5.3
Plugin Notes Plus: 1.2.6
SchedulePress: 4.2.7
Shortcodes Ultimate: 5.13.2
Starter Templates: 3.4.0
Tutor LMS: 2.2.3
Tutor LMS Elementor Addons: 2.1.1
Ultimate Dashboard: 3.7.6
UpdraftPlus - Backup/Restore: 1.23.9
WooCommerce: 8.0.2
WooCommerce Payments: 6.3.2
WooCommerce PayPal Payments: 2.2.0
WooCommerce Shipping & Tax: 2.3.3
WooCommerce Stripe Gateway: 7.5.0
WPForms Lite: 1.8.2.3

-- User Browser --

User Agent String:        Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/115.0.0.0 Safari/537.36 Edg/115.0.1901.203

-- Webserver Configuration --

PHP Version:              7.4.33
MySQL Version:            5.5.5
Web Server Info:          Apache
Platform:                 Linux

-- PHP Configuration --

PHP Memory Limit:         256M
PHP Safe Mode:            No
PHP Upload Max Size:      128M
PHP Post Max Size:        128M
PHP Upload Max Filesize:  128M
PHP Time Limit:           300
PHP Max Input Vars:       2500
Display Errors:           N/A
PHP Arg Separator:        &
PHP Allow URL File Open:  Yes

-- PHP Extensions --

fsockopen:                Your server supports fsockopen.
cURL:                     Your server supports cURL.
SOAP Client:              Your server has the SOAP Client enabled.
SUHOSIN:                  Your server does not have SUHOSIN installed.

### End System Info ###

**Comment by anomiex** [comment]
At first glance, my best guess here is that one of the many other plugins is somehow loading an older version of `Automattic\Jetpack\Sync\Settings` (from jetpack-sync package version 1.51.0 or earlier?) before Jetpack registers its later version. All the other classes in the trace come from Jetpack's copy.

@Automattic/jetpack-kernel, any more insight?

**Comment by zaerl** [comment]
@jeherve I think we can close this. I can't replicate it in WordPress 6.7 / Jetpack ~14, and the method [is declared](https://github.com/Automattic/jetpack/blob/trunk/projects/packages/sync/src/class-settings.php#L702).
