### ISSUE TITLE
Fatal Error: Jetpack CRM plugin 

### ISSUE THREAD

**Issue by brittanygray902** [Automattic/jetpack#34687]
### Impacted plugin

CRM

### Quick summary

User is unable to delete segments created with Jetpack CRM Extension: Advanced Segments plugin. Running php-errors in CLI provided Fatal error for Jetpack CRM. 

ZD-7465293

### Steps to reproduce

1. Have Jetpack CRM & Jetpack CRM Extension: Advanced Segments installed (with segments created)
2. Go to: Contacts > Segments 
3. Attempt to delete segment

Result: Pop up: "Could not delete!" 

### A clear and concise description of what you expected to happen.

With both the Jetpack CRM & Jetpack Advanced Segments plugin you should be able to properly delete segments. 

### What actually happened

When you attempt to delete segments you get a pop up that says,  "Could not delete!" 

### Impact

One

### Available workarounds?

No but the platform is still usable

### Platform (Simple and/or Atomic)

Atomic

### Logs or notes

Fatal error related to Jetpack CRM:

```
[17-Dec-2023 18:12:01 UTC] PHP Fatal error:  Uncaught Error: Call to undefined function jpcrm_api_forbidden_request() in /srv/htdocs/wp-content/plugins/zero-bs-crm/includes/ZeroBSCRM.AJAX.php:3744
Stack trace:
#0 /wordpress/core/6.4.2/wp-includes/class-wp-hook.php(324): zeroBSCRM_AJAX_enactListViewBulkAction('')
#1 /wordpress/core/6.4.2/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters('', Array)
#2 /wordpress/core/6.4.2/wp-includes/plugin.php(517): WP_Hook->do_action(Array)
#3 /wordpress/core/6.4.2/wp-admin/admin-ajax.php(188): do_action('wp_ajax_enactLi...')
#4 {main}
  thrown in /srv/htdocs/wp-content/plugins/zero-bs-crm/includes/ZeroBSCRM.AJAX.php on line 3744
[17-Dec-2023 18:13:21 UTC] PHP Notice:  Function WP_Scripts::localize was called incorrectly. The $l10n parameter must be an array. To pass arbitrary data to scripts, use the wp_add_inline_script() function instead. Please see <a>Debugging in WordPress</a> for more information. (This message was added in version 5.7.0.) in /wordpress/core/6.4.2/wp-includes/functions.php on line 6031
[17-Dec-2023 18:13:26 UTC] PHP Notice:  Function WP_Scripts::localize was called incorrectly. The $l10n parameter must be an array. To pass arbitrary data to scripts, use the wp_add_inline_script() function instead. Please see <a>Debugging in WordPress</a> for more information. (This message was added in version 5.7.0.) in /wordpress/core/6.4.2/wp-includes/functions.php on line 6031
```

**Comment by coder-karen** [comment]
Thanks for reporting this!

This looks to be related: https://github.com/Automattic/jetpack/pull/34586

**Comment by coder-karen** [comment]
@brittanygray902 This should now be fixed as of the latest release we just put out today - Jetpack CRM v6.3.2.

**Comment by jinnypark** [comment]
I've replied to user asking to update to the latest version, @coder-karen
