### ISSUE TITLE
JSON API: Various notices and fatal when publishing from Calypso

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#3739]
```[27-Apr-2016 04:24:19 UTC] PHP Notice:  Undefined index: user_id in /home/kraftbj/public_html/wp-content/plugins/jetpack/sal/class.json-api-token.php on line 45
[27-Apr-2016 04:24:19 UTC] PHP Notice:  Undefined index: scope in /home/kraftbj/public_html/wp-content/plugins/jetpack/sal/class.json-api-token.php on line 46
[27-Apr-2016 04:24:19 UTC] PHP Notice:  Undefined index: client_id in /home/kraftbj/public_html/wp-content/plugins/jetpack/sal/class.json-api-token.php on line 47
[27-Apr-2016 04:24:19 UTC] PHP Notice:  Undefined index: external_user_id in /home/kraftbj/public_html/wp-content/plugins/jetpack/sal/class.json-api-token.php on line 48
[27-Apr-2016 04:24:19 UTC] PHP Notice:  Undefined index: external_user_code in /home/kraftbj/public_html/wp-content/plugins/jetpack/sal/class.json-api-token.php on line 49
[27-Apr-2016 04:24:19 UTC] PHP Notice:  Undefined index: auth in /home/kraftbj/public_html/wp-content/plugins/jetpack/sal/class.json-api-token.php on line 50
[27-Apr-2016 04:24:19 UTC] PHP Fatal error:  Class 'Jetpack_Post' not found in /home/kraftbj/public_html/wp-content/plugins/jetpack/sal/class.json-api-site-jetpack.php on line 123```

**Comment by kraftbj** [comment]
I'm trying to go down the rabbit hole a bit. Adding `require_once dirname( __FILE__ ) . '/class.json-api-post-jetpack.php';` to `class.json-api-site-jetpack.php` fixes that fatal, but then adds a new one:
`[27-Apr-2016 04:32:24 UTC] PHP Fatal error:  Call to undefined function wpcom_get_avatar_url() in /home/kraftbj/public_html/wp-content/plugins/jetpack/sal/class.json-api-post-base.php on line 472`

Editing that function to includes a non-wpcom fallback, e.g. 
```
	private function get_avatar_url( $email, $avatar_size = 96 ) {
		if ( function_exists( 'wpcom_get_avatar_url' ) ){
			$avatar_url = wpcom_get_avatar_url( $email, $avatar_size, '', true );
		}
		else {
			$avatar_url = get_avatar_url( $email, array( 'size' => $avatar_size ) );
		}
		if ( !$avatar_url || is_wp_error( $avatar_url ) ) {
			return '';
		}```

gives me a litany of notices, undefined variables, etc 

```
[27-Apr-2016 04:36:47 UTC] PHP Notice:  Undefined variable: post in /home/kraftbj/public_html/wp-content/plugins/jetpack/json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php on line 624
[27-Apr-2016 04:36:47 UTC] PHP Notice:  Trying to get property of non-object in /home/kraftbj/public_html/wp-content/plugins/jetpack/json-endpoints/class.wpcom-json-api-update-post-v1-2-endpoint.php on line 624
[27-Apr-2016 04:36:47 UTC] PHP Notice:  Undefined index: user_id in /home/kraftbj/public_html/wp-content/plugins/jetpack/sal/class.json-api-token.php on line 45
[27-Apr-2016 04:36:47 UTC] PHP Notice:  Undefined index: scope in /home/kraftbj/public_html/wp-content/plugins/jetpack/sal/class.json-api-token.php on line 46
[27-Apr-2016 04:36:47 UTC] PHP Notice:  Undefined index: client_id in /home/kraftbj/public_html/wp-content/plugins/jetpack/sal/class.json-api-token.php on line 47
[27-Apr-2016 04:36:47 UTC] PHP Notice:  Undefined index: external_user_id in /home/kraftbj/public_html/wp-content/plugins/jetpack/sal/class.json-api-token.php on line 48
[27-Apr-2016 04:36:47 UTC] PHP Notice:  Undefined index: external_user_code in /home/kraftbj/public_html/wp-content/plugins/jetpack/sal/class.json-api-token.php on line 49
[27-Apr-2016 04:36:47 UTC] PHP Notice:  Undefined index: auth in /home/kraftbj/public_html/wp-content/plugins/jetpack/sal/class.json-api-token.php on line 50
```

Punting and reverting back to a previous version so I can continue on with the issue I originally tried to tackle. Hope this helps! 

cc: @gravityrail

**Comment by kraftbj** [comment]
Noting that via Calypso, it reports that publishing the post is failing. In reality, it still publishes.

**Comment by jeherve** [comment]
Noting that this fatal also stops you from getting a list of posts in `wordpress.com/posts`. Here is a stack trace, if it can help:

```
[27-Apr-2016 13:13:39 UTC] PHP Fatal error:  Uncaught Error: Class 'Jetpack_Post' not found in /wp-content/plugins/jetpack/sal/class.json-api-site-jetpack.php:123
Stack trace:
#0 /wp-content/plugins/jetpack/sal/class.json-api-site-base.php(109): Jetpack_Site->wrap_post(Object(WP_Post), 'display')
#1 /wp-content/plugins/jetpack/json-endpoints/class.wpcom-json-api-post-v1-1-endpoint.php(128): SAL_Site->get_post_by_id(16902, 'display')
#2 /wp-content/plugins/jetpack/json-endpoints/class.wpcom-json-api-post-v1-1-endpoint.php(101): WPCOM_JSON_API_Post_v1_1_Endpoint->get_sal_post_by('ID', 16902, 'display')
#3 /wp-content/plugins/jetpack/json-endpoints/class.wpcom-json-api-list-posts-v1-1-endpoint.php(279): WPCOM_JSON_API_Post_v1_1_Endpoint->get_post_by('ID', 16902, 'display')
#4 /wp-content/plugins/jetpack/class.json-api.php(332): WPCOM_JSON_API_List_Posts_v1_1_Endpoint->callback('/sites/jeremy.h...', '1')
#5 /wp-content/plugins/jetpack/class.json-api.php(316): WPCOM_JSON_API->process_request(Object(WPCOM_JSON_API_List_Posts_v1_1_Endpoint), Array)
#6 /wp-content/plugins/jetpack/class.jetpack-xmlrpc-server.php(473): WPCOM_JSON_API->serve(false)
#7 /wp-includes/class-IXR.php(532): Jetpack_XMLRPC_Server->json_api(Array)
#8 /wp-includes/class-IXR.php(617): IXR_Server->call('jetpack.jsonAPI', Array)
#9 /wp-includes/class-IXR.php(520): IXR_Server->multiCall(Array)
#10 /wp-includes/class-IXR.php(470): IXR_Server->call('system.multical...', Array)
#11 /wp-includes/class-IXR.php(432): IXR_Server->serve('<?xml version="...')
#12 /wp-includes/class-IXR.php(440): IXR_Server->__construct(Array, false, false)
#13 /wp-includes/class-wp-xmlrpc-server.php(197): IXR_Server->IXR_Server(Array)
#14 /xmlrpc.php(84): wp_xmlrpc_server->serve_request()
#15 {main}
  thrown in /wp-content/plugins/jetpack/sal/class.json-api-site-jetpack.php on line 123
```

**Comment by dereksmart** [comment]
@kraftbj @jeherve are you experiencing this in production or on master? If it's in master, can you please move the milestone to 4.1.0 as we don't plan on shipping the breaking json api changes (#3639) until then.

**Comment by jeherve** [comment]
It's on master for me. Isn't there a way to fix this in `master` though, so people running `'master` or the Beta plugin with the "Bleeding edge" option can continue to use Calypso?

**Comment by dereksmart** [comment]
@jeherve Yep, the breaking changes must have made their way to master-stable (where bleeding edge comes from).  I think we're at the mercy of @gravityrail or the next person who has time to dig into this and can get a patch in.  

Of course reverting it from master-stable is an (not ideal) option as well.

**Comment by kraftbj** [comment]
On `master` for me too. Moving to 4.1.0, but yeah, we should revert this and punt back to a PR or get it fixed soonish.

**Comment by kraftbj** [comment]
Any word on this? It's kinda annoying to not be able to use Calypso on master.

**Comment by dereksmart** [comment]
@gravityrail do we just need some `class_exists()` & `isset()` checks here? or do you suspect it's something bigger?

**Comment by kraftbj** [comment]
I think this is fine as a 4.1 milestone. The code that's broken isn't in the 4.x branch, right?

**Comment by gravityrail** [comment]
I'm fixing this now... should we perhaps have some automated tests of the API inside Jetpack?

**Comment by gravityrail** [comment]
This is now fixed (though there may be other issues from the merged code that we have yet to discover)
