### ISSUE TITLE
Fatal error: Uncaught Error: Cannot use string offset as an array - after wordpress migration

### ISSUE THREAD

**Issue by machinekoder** [Automattic/jetpack#7986]
#### Steps to reproduce the issue
I migrated my WordPress site to a new server with PHP 7.1 and MySQL 5.1.73. After the migration I encounter problems with Jetpack, reinstall does not help.

#### What I expected

That Jetpack migration to a new server works without problems.

#### What happened instead

Following error message:

```

Warning: Illegal string offset '5.4' in /var/www/virtual/mkoder/html/wp-content/plugins/jetpack/class.jetpack.php on line 2411

Fatal error: Uncaught Error: Cannot use string offset as an array in /var/www/virtual/mkoder/html/wp-content/plugins/jetpack/class.jetpack.php:2411 Stack trace: #0 /var/www/virtual/mkoder/html/wp-content/plugins/jetpack/class.jetpack.php(2324): Jetpack::get_file_data('/var/www/virtua...', Array) #1 /var/www/virtual/mkoder/html/wp-content/plugins/jetpack/class.jetpack.php(2126): Jetpack::get_module('/var/www/virtua...') #2 /var/www/virtual/mkoder/html/wp-content/plugins/jetpack/class.jetpack.php(2501): Jetpack::get_available_modules() #3 /var/www/virtual/mkoder/html/wp-content/plugins/jetpack/class.jetpack.php(2704): Jetpack::is_module('manage') #4 /var/www/virtual/mkoder/html/wp-content/plugins/jetpack/class.jetpack.php(409): Jetpack::activate_module('manage', false, false) #5 /var/www/virtual/mkoder/html/wp-content/plugins/jetpack/class.jetpack.php(2968): Jetpack::activate_manage() #6 /var/www/virtual/mkoder/html/wp-includes/class-wp-hook.php(298): Jetpack::do_version_bump('5.4:1507888960', false) #7 /var/www/virtual/mko in /var/www/virtual/mkoder/html/wp-content/plugins/jetpack/class.jetpack.php on line 2411
```

**Comment by jeherve** [comment]
Thanks for the report. I'm closing to close your issue as it was already reported elsewhere, so you can follow the issue here instead: #7097
