### ISSUE TITLE
Can't build in Windows Subsystem for Linux, maybe due to old node-sass

### ISSUE THREAD

**Issue by Viper007Bond** [Automattic/jetpack#8267]
I checked out a copy via git and then tried to build Jetpack under WSL. I'm using Ubuntu 16.04.3.

I manually ran `yarn install` first because I was getting lots of errors like the following.

```
error An unexpected error occurred: "ENOENT: no such file or directory, copyfile '/home/viper007bond/.cache/yarn/v1/npm-pako-0.2.9-f3f7522f4ef782348da8161bad9ecfd51bf83a75/lib/inflate.js' -> '/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/pako/lib/inflate.js'".
```

The file varied per run and I'm guessing it was due to `--check-files`. Anyway, after running `yarn install` a few times, I ran `yarn build`:

```
viper007bond@AlexSurface:/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack$ yarn build
yarn run v1.3.2
$ yarn install-if-deps-outdated && yarn build-client
$ yarn check 2> /dev/null || yarn install --check-files
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
success Folder in sync.
$ gulp
[16:54:24] Requiring external module babel-register
/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/gulp-sass/node_modules/node-sass/lib/binding.js:13
      throw new Error(errors.unsupportedEnvironment());
      ^

Error: Node Sass does not yet support your current environment: Linux 64-bit with Unsupported runtime (57)
For more information on which environments are supported please see:
https://github.com/sass/node-sass/releases/tag/v3.13.1
    at module.exports (/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/gulp-sass/node_modules/node-sass/lib/binding.js:13:13)
    at Object.<anonymous> (/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/gulp-sass/node_modules/node-sass/lib/index.js:14:35)
    at Module._compile (module.js:635:30)
    at Module._extensions..js (module.js:646:10)
    at Object.require.extensions.(anonymous function) [as .js] (/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

So I tried updating all dependencies to their latest version using this:

```
yarn global add npm-check-updates
ncu --upgrade --upgradeAll && yarn upgrade
```

I did that thinking it might be an issue with the old version of `node-sass` because I use it without issue in [one of my plugins](https://github.com/Viper007Bond/regenerate-thumbnails/tree/dev/v3-rewrite) and sure enough that seemed to fix the issue. However now `csstidy` is throwing an error:

```
viper007bond@AlexSurface:/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack$ yarn build-client
yarn run v1.3.2
$ gulp
[17:26:12] Requiring external module babel-register
[17:26:14] Using gulpfile /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/gulpfile.babel.js
[17:26:14] Starting 'react:build'...
[17:26:15] Starting 'frontendcss:separate'...
[17:26:15] Starting 'admincss'...
[17:26:15] Starting 'admincss:rtl'...
[17:26:15] Starting 'old-sass'...
[17:26:15] Starting 'old-sass:rtl'...
[17:26:15] Starting 'check:DIR'...
[17:26:15] Starting 'php:lint'...
[17:26:15] Starting 'js:hint'...
[17:26:15] Starting 'php:module-headings'...
[17:26:15] Starting 'gutenpack'...
[17:26:16] Finished 'php:module-headings' after 1.16 s
[17:26:22] Finished 'gutenpack' after 7.06 s
events.js:188
      throw err;
      ^

Error: Unhandled "error" event. (Ignoring local @import of "../../custom-css/csstidy/modules/custom-css/csstidy/cssparsed.css" as resource is missing.)
    at DestroyableTransform.emit (events.js:186:19)
    at DestroyableTransform.onerror (/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/readable-stream/lib/_stream_readable.js:633:52)
    at emitOne (events.js:116:13)
    at DestroyableTransform.emit (events.js:211:7)
    at onwriteError (/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/readable-stream/lib/_stream_writable.js:427:12)
    at onwrite (/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/readable-stream/lib/_stream_writable.js:448:11)
    at WritableState.onwrite (/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/readable-stream/lib/_stream_writable.js:169:5)
    at afterTransform (/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/readable-stream/lib/_stream_transform.js:104:3)
    at TransformState.afterTransform (/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/readable-stream/lib/_stream_transform.js:79:12)
    at /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/gulp-clean-css/index.js:38:16
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any ideas?

**Comment by Viper007Bond** [comment]
I tried updating just `node-sass` to the latest version but I get this error during `yarn install`:

```
viper007bond@AlexSurface:/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack$ yarn install
yarn install v1.3.2
info No lockfile found.
[1/5] Validating package.json...
[2/5] Resolving packages...
warning babel-core > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning babel-preset-es2015@6.24.1: 🙌  Thanks for using Babel: we recommend using babel-preset-env now: please read babeljs.io/env to update!
warning gulp > vinyl-fs > glob-stream > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning gulp > vinyl-fs > glob-watcher > gaze > globule > glob > graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
warning gulp-check > through2 > xtend > object-keys@0.4.0:
warning gulp-clean-css@2.4.0: breaking changes from clean-css 4.x. Please install gulp-clean-css 3.x
warning gulp-phplint > gulp-messenger > chalkline@0.0.4: No longer sponsored by CT - please visit http://niftylettuce.com for more info
warning jshint > minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning jshint > cli > glob > minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning grunt > minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
warning mocha > to-iso-string@0.0.2: to-iso-string has been deprecated, use @segment/to-iso-string instead.
warning mocha > jade@0.26.3: Jade has been renamed to pug, please install the latest version of pug instead of jade
[3/5] Fetching packages...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[-/5] ⠐ waiting...
[2/5] ⠐ phantomjs-prebuilt: Extracting tar contents (via spawned process)
[3/5] ⠈ node-sass: verb node dev dir /home/viper007bond/.node-gyp/8.9.1
[-/5] ⠈ waiting...
error /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/gulp-sass/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/gulp-sass/node_modules/node-sass
Output:
Building: /usr/bin/node /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.1
gyp verb command install [ '8.9.1' ]
gyp verb install input version string "8.9.1"
gyp verb install installing version: 8.9.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.1
gyp verb build dir attempting to create "build" dir: /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/gulp-sass/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/gulp-sass/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/gulp-sass/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/gulp-sass/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/gulp-sass/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/gulp-sass/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/viper007bond/.node-gyp/8.9.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/viper007bond/.node-gyp/8.9.1',
gyp info spawn args   '-Dnode_gyp_dir=/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/viper007bond/.node-gyp/8.9.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/gulp-sass/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/viper007bond/.node-gyp/8.9.1
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/which/which.js:80:29)
gyp ERR! stack     at /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/which/which.js:89:16
gyp ERR! stack     at /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.4.0-43-Microsoft
gyp ERR! command "/usr/bin/node" "/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v8.9.1
```

**Comment by oskosk** [comment]
Just checking... How did you install yarn ? was it via `apt-get`? (https://yarnpkg.com/en/docs/install#linux-tab)

**Comment by Viper007Bond** [comment]
I honestly can't remember but presumably yes, I'd have followed those instructions. Just to be sure, I even reinstalled it just now:

```
viper007bond@AlexSurface:~$ yarn --version
1.3.2
viper007bond@AlexSurface:~$ sudo apt remove yarn
[sudo] password for viper007bond:
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following packages will be REMOVED:
  yarn
0 upgraded, 0 newly installed, 1 to remove and 0 not upgraded.
After this operation, 4,125 kB disk space will be freed.
Do you want to continue? [Y/n]
(Reading database ... 31077 files and directories currently installed.)
Removing yarn (1.3.2-1) ...
viper007bond@AlexSurface:~$ node --version
v8.9.1
viper007bond@AlexSurface:~$ curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add -
OK
viper007bond@AlexSurface:~$ echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list
deb https://dl.yarnpkg.com/debian/ stable main
viper007bond@AlexSurface:~$ sudo apt-get update && sudo apt-get install yarn
Hit:1 http://archive.ubuntu.com/ubuntu xenial InRelease
Get:2 http://security.ubuntu.com/ubuntu xenial-security InRelease [102 kB]
Get:3 http://archive.ubuntu.com/ubuntu xenial-updates InRelease [102 kB]
Hit:4 https://dl.yarnpkg.com/debian stable InRelease
Hit:5 https://deb.nodesource.com/node_8.x xenial InRelease
Get:6 http://archive.ubuntu.com/ubuntu xenial-backports InRelease [102 kB]
Get:7 http://archive.ubuntu.com/ubuntu xenial-updates/main amd64 Packages [670 kB]
Get:8 http://archive.ubuntu.com/ubuntu xenial-updates/main Translation-en [280 kB]
Get:9 http://security.ubuntu.com/ubuntu xenial-security/main amd64 Packages [397 kB]
Get:10 http://archive.ubuntu.com/ubuntu xenial-updates/universe amd64 Packages [561 kB]
Get:11 http://archive.ubuntu.com/ubuntu xenial-updates/universe Translation-en [227 kB]
Get:12 http://security.ubuntu.com/ubuntu xenial-security/main Translation-en [175 kB]
Get:13 http://archive.ubuntu.com/ubuntu xenial-backports/universe amd64 Packages [6,624 B]
Get:14 http://archive.ubuntu.com/ubuntu xenial-backports/universe Translation-en [3,768 B]
Get:15 http://security.ubuntu.com/ubuntu xenial-security/universe amd64 Packages [183 kB]
Get:16 http://security.ubuntu.com/ubuntu xenial-security/universe Translation-en [96.5 kB]
Fetched 2,906 kB in 8s (340 kB/s)
Reading package lists... Done
Reading package lists... Done
Building dependency tree
Reading state information... Done
The following NEW packages will be installed:
  yarn
0 upgraded, 1 newly installed, 0 to remove and 20 not upgraded.
Need to get 0 B/670 kB of archives.
After this operation, 4,125 kB of additional disk space will be used.
Selecting previously unselected package yarn.
(Reading database ... 31059 files and directories currently installed.)
Preparing to unpack .../archives/yarn_1.3.2-1_all.deb ...
Unpacking yarn (1.3.2-1) ...
Setting up yarn (1.3.2-1) ...
viper007bond@AlexSurface:~$ yarn --version
1.3.2
```

It still fails though: 

```
viper007bond@AlexSurface:/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev$ yarn install
yarn install v1.3.2
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info There appears to be trouble with your network connection. Retrying...
info fsevents@1.1.3: The platform "linux" is incompatible with this module.
info "fsevents@1.1.3" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
[5/5] Building fresh packages...
[-/5] ⠁ waiting...
[2/5] ⠂ phantomjs-prebuilt: Extracting tar contents (via spawned process)
[3/5] ⠂ node-sass: gyp
[-/5] ⠂ waiting...
error /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/gulp-sass/node_modules/node-sass: Command failed.
Exit code: 1
Command: node scripts/build.js
Arguments:
Directory: /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/gulp-sass/node_modules/node-sass
Output:
Building: /usr/bin/node /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/node-gyp/bin/node-gyp.js rebuild --verbose --libsass_ext= --libsass_cflags= --libsass_ldflags= --libsass_library=
gyp info it worked if it ends with ok
gyp verb cli [ '/usr/bin/node',
gyp verb cli   '/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/node-gyp/bin/node-gyp.js',
gyp verb cli   'rebuild',
gyp verb cli   '--verbose',
gyp verb cli   '--libsass_ext=',
gyp verb cli   '--libsass_cflags=',
gyp verb cli   '--libsass_ldflags=',
gyp verb cli   '--libsass_library=' ]
gyp info using node-gyp@3.6.2
gyp info using node@8.9.1 | linux | x64
gyp verb command rebuild []
gyp verb command clean []
gyp verb clean removing "build" directory
gyp verb command configure []
gyp verb check python checking for Python executable "python2" in the PATH
gyp verb `which` succeeded python2 /usr/bin/python2
gyp verb check python version `/usr/bin/python2 -c "import platform; print(platform.python_version());"` returned: "2.7.12\n"
gyp verb get node dir no --target version specified, falling back to host node version: 8.9.1
gyp verb command install [ '8.9.1' ]
gyp verb install input version string "8.9.1"
gyp verb install installing version: 8.9.1
gyp verb install --ensure was passed, so won't reinstall if already installed
gyp verb install version is already installed, need to check "installVersion"
gyp verb got "installVersion" 9
gyp verb needs "installVersion" 9
gyp verb install version is good
gyp verb get node dir target node version installed: 8.9.1
gyp verb build dir attempting to create "build" dir: /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/gulp-sass/node_modules/node-sass/build
gyp verb build dir "build" dir needed to be created? /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/gulp-sass/node_modules/node-sass/build
gyp verb build/config.gypi creating config file
gyp verb build/config.gypi writing out config file: /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/gulp-sass/node_modules/node-sass/build/config.gypi
gyp verb config.gypi checking for gypi file: /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/gulp-sass/node_modules/node-sass/config.gypi
gyp verb common.gypi checking for gypi file: /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/gulp-sass/node_modules/node-sass/common.gypi
gyp verb gyp gyp format was not specified; forcing "make"
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/gulp-sass/node_modules/node-sass/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/viper007bond/.node-gyp/8.9.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/viper007bond/.node-gyp/8.9.1',
gyp info spawn args   '-Dnode_gyp_dir=/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/viper007bond/.node-gyp/8.9.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/gulp-sass/node_modules/node-sass',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp verb command build []
gyp verb build type Release
gyp verb architecture x64
gyp verb node dev dir /home/viper007bond/.node-gyp/8.9.1
gyp ERR! build error
gyp ERR! stack Error: not found: make
gyp ERR! stack     at getNotFoundError (/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/which/which.js:13:12)
gyp ERR! stack     at F (/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/which/which.js:68:19)
gyp ERR! stack     at E (/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/which/which.js:80:29)
gyp ERR! stack     at /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/which/which.js:89:16
gyp ERR! stack     at /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/isexe/index.js:42:5
gyp ERR! stack     at /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/isexe/mode.js:8:5
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:152:21)
gyp ERR! System Linux 4.4.0-43-Microsoft
gyp ERR! command "/usr/bin/node" "/mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/node-gyp/bin/node-gyp.js" "rebuild" "--verbose" "--libsass_ext=" "--libsass_cflags=" "--libsass_ldflags=" "--libsass_library="
gyp ERR! cwd /mnt/c/work/jetpack-sandbox/wp-content/plugins/jetpack-dev/node_modules/gulp-sass/node_modules/node-sass
gyp ERR! node -v v8.9.1
```

**Comment by oskosk** [comment]
"Looks" like building `libsass` is demanding `make` to be there in your box and it can't find it. Could you check if this is the case and if installing it helps? I know it's a PITA but there's an explanation which comes from a feature introduced in Node 8.x which makes the libsass be built instead of downloaded. Sorry

**Comment by Viper007Bond** [comment]
Yeah, turns out I didn't have `make` installed. Installing it fixed the issue -- thanks!

**Comment by oskosk** [comment]
niceeeeeee!
