### ISSUE TITLE
6.1 Upgrade: Fatal when upgrading via WP-CLI

### ISSUE THREAD

**Issue by kraftbj** [Automattic/jetpack#9477]
As reported in the forums and I saw when upgrading myself. The upgrade goes through and is successful. The function is new ( https://github.com/Automattic/jetpack/blob/master/functions.global.php#L167 ).

My guess is something to do with calling a new function during the upgrade process?

```
Enabling Maintenance mode...
Downloading update from https://downloads.wordpress.org/plugin/jetpack.6.1.zip...
Unpacking the update...
Installing the latest version...
Removing the old version of the plugin...
Plugin updated successfully.
Disabling Maintenance mode...
+---------+-------------+-------------+---------+
| name | old_version | new_version | status |
+---------+-------------+-------------+---------+
| jetpack | 6.0 | 6.1 | Updated |
+---------+-------------+-------------+---------+
Success: Updated 1 of 1 plugins.
PHP Fatal error: Uncaught Error: Call to undefined function jetpack_json_wrap() in /jetpack/sync/class.jetpack-sync-json-deflate-array-codec.php:27
Stack trace:
#0 /jetpack/sync/class.jetpack-sync-json-deflate-array-codec.php(17): Jetpack_Sync_JSON_Deflate_Array_Codec->json_serialize(Array)
#1 /jetpack/sync/class.jetpack-sync-sender.php(177): Jetpack_Sync_JSON_Deflate_Array_Codec->encode(Array)
#2 /jetpack/sync/class.jetpack-sync-sender.php(219): Jetpack_Sync_Sender->get_items_to_send(Object(Jetpack_Sync_Queue_Buffer), true)
#3 /jetpack/sync/class.jetpack-sync-sender.php(124): Jetpack_Sync_Sender->do_sync_for_queue(Object(Jetpack_Sync_Queue))
#4 /jetpack/sync/class.jetpack-sync-sender.php(88): Jetpack_Sync_Sender->do_sync_and_set_delays(Object(Jetpack_Sync_Queue))
#5 / in /jetpack/sync/class.jetpack-sync-json-deflate-array-codec.php on line 27
```

**Comment by jeherve** [comment]
cc @enejb.

Introduced in #9382

**Comment by enejb** [comment]
So what is going on is that the update happends and then when we send that info to .com via sync we get a fatal error. Not ideal. But it should only happen once 

cc: @lezama so you are aware of it for next time as well.

**Comment by lezama** [comment]
not sure I understand how this is possible unless we are requiring `functions.global.php` too late?

**Comment by lezama** [comment]
shouldn't we move [this](https://github.com/Automattic/jetpack/blob/03a5e33aa9cd108aa1be7e0dd9e9ee7d29b306ba/jetpack.php#L59) higher up?

**Comment by enejb** [comment]
The way I explain this fateling is sync want to store data on shutdown and it load the new (6.1) code to do so.
