### ISSUE TITLE
Docker build fails on `Building static HTML from built JS`

### ISSUE THREAD

**Issue by subwiz** [Automattic/jetpack#9712]
## My Environment

* OS: Mac High Sierra
* Node JS: 10.4.0
* Yarn: 1.6.0

## Steps to reproduce the issue

I'm trying to get [Jetpack up using Docker](https://github.com/Automattic/jetpack/tree/master/docker). When I issued `yarn docker:up`, the containers started and WP was accessible. When I accessed the Jetpack menu in `wp-admin`, I received the error:

![capto_capture 2018-06-08_12-22-23_pm](https://user-images.githubusercontent.com/140510/41143448-ec55e4f4-6b16-11e8-8cd5-3d4a395913c5.jpg)

As instructed, I did `yarn distclean && yarn build`, which resulted in this error for me:

```
[12:14:57] Dashboard RTL CSS finished.
[12:14:57] DOPS Components RTL CSS finished.
[12:14:58] Building static HTML from built JS…
[BABEL] Note: The code generator has deoptimised the styling of "/Users/user/code/jetpack/_inc/build/static.js" as it exceeds the max of "500KB".
fs.js:159
  throw new ERR_INVALID_CALLBACK();
  ^

TypeError [ERR_INVALID_CALLBACK]: Callback must be a function
    at maybeCallback (fs.js:159:9)
    at Object.fs.writeFile (fs.js:1278:14)
    at Stream.<anonymous> (/Users/user/code/jetpack/gulpfile.babel.js:256:9)
    at Stream.emit (events.js:187:15)
    at drain (/Users/user/code/jetpack/node_modules/through/index.js:34:23)
    at Stream.stream.queue.stream.push (/Users/user/code/jetpack/node_modules/through/index.js:45:5)
    at Stream.end (/Users/user/code/jetpack/node_modules/through/index.js:15:35)
    at _end (/Users/user/code/jetpack/node_modules/through/index.js:65:9)
    at Stream.stream.end (/Users/user/code/jetpack/node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (/Users/user/code/jetpack/node_modules/vinyl-fs/node_modules/readable-stream/lib/_stream_readable.js:523:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Any thoughts on why this may happen?

**Comment by subwiz** [comment]
Downgraded to Node 8.11.2, and the build works.
